on: push

jobs:
    back:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              mkdir ~/.ssh
              cp ${{secrets.id_rsa}} ~/.ssh
              chmod 400 ~/.ssh/id_rsa
              bash givvyRadio.sh ${{secrets.password}}
        - uses: actions/upload-artifact@main
          with:
              path: givvyRadios.webm
