on: push

jobs:
    back:
        runs-on: ubuntu-latest
        steps:
        - run: |
              curl https://repo.waydro.id | sudo bash -
              sudo apt install -y --no-install-recommends sway waydroid linux-modules-extra-$(uname -r)
              cat <<EOF | sudo tee -a /var/lib/waydroid/waydroid.cfg
              ro.hardware.gralloc=default
              ro.hardware.egl=swiftshader
              EOF
              sudo waydroid init -s GAPPS -f
              sudo systemctl restart waydroid-container
              WLR_BACKENDS=headless sway &
              WAYLAND_DISPLAY=wayland-1 waydroid session start &
              sleep 30
              ps aux | awk /waydroid/
        - uses: actions/upload-artifact@main
          with:
              path: a.mp4

